urls: 
  van der linden: https://www.vanderlinden.nl/woning-huren/
  vb en t: https://vbtverhuurmakelaars.nl/woningen
email:
  from: 'koen.smallegange@gmail.com'
  to: 'koen.smallegange@live.nl'
  smtp_server: 'smtp.gmail.com'
  smtp_port: 587
general:
  city: 'Rotterdam'
  time_interval: 60